name: lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

env:
  WORKING_DIR: terraform/

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6

      - name: setup terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # pin@v4.0.0
        with:
          terraform_version: 1.14.8

      - name: setup tflint
        uses: terraform-linters/setup-tflint@b480b8fcdaa6f2c577f8e4fa799e89e756bb7c93 # pin@v6.2.2
        with:
          tflint_version: v0.61.0

      - name: terraform fmt
        run: terraform fmt -check -recursive

      - name: tflint init
        run: tflint --init

      - name: tflint
        run: tflint --recursive
